### ISSUE TITLE
Error in readme

### ISSUE THREAD

**Issue by Blemming** [HeartofPhos/exile-export#1]
>Run dat2json ./game ./exports ./dat-list.txt

should be

>Run dat2json ./game/Content.ggpk ./exports ./dat-list.txt

otherwise you get 
````
Could not read _.index.bin
Could not open index

**Comment by HeartofPhos** [comment]
I believe this depends on whether you use the steam version or not, at the very least the current info is correct for steam & steam bundle downloads

**Comment by Blemming** [comment]
Oh that must be it, i'm using the GGG launcher

EDIT: awesome project btw really cool to be able to extract dat to json in a docker :)
